/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login and receive auth cookies
         * @description On success, sets two HttpOnly cookies: `accessToken` (15 min) and `refreshToken` (7 days). Include `credentials: "include"` in fetch calls.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh the access token
         * @description Reads the `refreshToken` cookie and issues new auth cookies.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout and clear auth cookies */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current authenticated user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterBody: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /**
             * @description Must contain at least one uppercase letter and one number
             * @example Password1
             */
            password: string;
            /** @example Jane Doe */
            name: string;
        };
        LoginBody: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example Password1 */
            password: string;
        };
        User: {
            /**
             * Format: uuid
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id?: string;
            /**
             * Format: email
             * @example user@example.com
             */
            email?: string;
            /** @example Jane Doe */
            name?: string;
            /**
             * @example user
             * @enum {string}
             */
            role?: "user" | "admin";
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            updatedAt?: string;
        };
        ErrorResponse: {
            /** @example Invalid credentials */
            error?: string;
        };
        MessageResponse: {
            data?: {
                /** @example Success */
                message?: string;
            };
        };
        ValidationErrorResponse: {
            /** @example Validation failed */
            error?: string;
            details?: {
                /** @example email */
                field?: string;
                /** @example Invalid email address */
                message?: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterBody"];
            };
        };
        responses: {
            /** @description User registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["User"];
                    };
                };
            };
            /** @description Email already in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginBody"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            user?: components["schemas"]["User"];
                        };
                    };
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tokens refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Missing or invalid refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["User"];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}

export type ApiDayPlanSummary = {
  id: string;
  dayNumber: number;
  label: string;
  date: string;
  isRestDay: boolean;
};

export type ApiMealItem = {
  id: string;
  name: string;
  quantity: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
};

export type ApiMeal = {
  id: string;
  type: "breakfast" | "snack" | "lunch" | "dinner";
  sortOrder: number;
  time: string;
  totalCalories: number;
  totalProtein: number;
  totalCarbs: number;
  totalFat: number;
  items: ApiMealItem[];
};

export type ApiExercise = {
  id: string;
  name: string;
  sets: number;
  reps: string;
  rest: string;
  muscle: string;
  notes: string | null;
};

export type ApiWorkout = {
  id: string;
  name: string;
  type: string;
  duration: string;
  exercises: ApiExercise[];
} | null;

export type ApiDayPlanDetail = ApiDayPlanSummary & {
  meals: ApiMeal[];
  workout: ApiWorkout;
};

export type ApiProgram = {
  id: string;
  title: string;
  goal: string;
  duration: string;
  weeks: number;
  level: string;
  calories: number;
  startDate: string;
  currentWeek: number;
  currentDay: number;
  completedDays: number;
  totalDays: number;
  adherenceRate: number;
};

export type ApiMealLog = {
  id: string;
  mealId: string;
  status: "pending" | "followed" | "modified" | "skipped";
  note: string | null;
  actualCalories: number | null;
};

export type ApiWorkoutLog = {
  id: string;
  workoutId: string;
  status: "pending" | "completed" | "skipped" | "modified";
  note: string | null;
};

export type Gender = "male" | "female";
export type ActivityLevel = "sedentary" | "light" | "moderate" | "active" | "very_active";
export type FitnessGoal = "lose_weight" | "gain_muscle" | "maintain" | "improve_endurance" | "general_health";

export type ApiUserProfile = {
  id: string;
  userId: string;
  age: number;
  gender: Gender;
  heightCm: number;
  weightKg: number;
  targetWeightKg: number | null;
  activityLevel: ActivityLevel;
  goal: FitnessGoal;
  injuries: string | null;
  dietaryNotes: string | null;
  completedAt: string | null;
};

export type CoachRequestStatus = "pending" | "accepted" | "rejected" | "completed";

// Matches coach.service.ts's listAvailable() shape exactly — no email, age is precomputed.
export type ApiCoach = {
  id: string;
  name: string;
  title: string | null;
  bio: string | null;
  gender: Gender | null;
  age: number | null;
  specialties: string[] | null;
  yearsExperience: number | null;
  certifications: string[] | null;
  rating: number | null;
  clientsCount: number;
  avatarUrl: string | null;
};

export type ApiCoachRequestCoach = {
  id: string;
  name: string;
};

export type ApiCoachRequest = {
  id: string;
  userId: string;
  coachId: string | null;
  coach?: ApiCoachRequestCoach | null;
  status: CoachRequestStatus;
  message: string | null;
  respondedAt: string | null;
  createdAt: string;
};

export type ApiCoachProfile = {
  id: string;
  userId: string;
  title: string | null;
  bio: string | null;
  gender: Gender | null;
  birthDate: string | null;
  specialties: string[] | null;
  yearsExperience: number | null;
  certifications: string[] | null;
  avatarUrl: string | null;
  rating: number | null;
  clientsCount: number;
};

export type ApiCoachProfileInput = {
  title?: string | null;
  bio?: string | null;
  gender?: Gender | null;
  birthDate?: string | null;
  specialties?: string[] | null;
  yearsExperience?: number | null;
  certifications?: string[] | null;
  avatarUrl?: string | null;
};

export type ApiCoachClientProfile = {
  age: number | null;
  gender: Gender | null;
  heightCm: number | null;
  weightKg: number | null;
  targetWeightKg: number | null;
  activityLevel: string | null;
  goal: string | null;
  injuries: string | null;
  dietaryNotes: string | null;
};

/** A request as a coach sees it: with the client attached, and their program if built. */
export type ApiCoachRequestWithClient = ApiCoachRequest & {
  user?: {
    id: string;
    name: string;
    profile?: ApiCoachClientProfile | null;
  } | null;
  program?: {
    id: string;
    title: string;
    status: ApiProgramStatus;
  } | null;
};

export type ApiProgramStatus = "draft" | "published";

export type ApiBuilderMealItem = {
  name: string;
  quantity: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
};

export type ApiBuilderMeal = {
  type: "breakfast" | "snack" | "lunch" | "dinner";
  time: string;
  items: ApiBuilderMealItem[];
};

export type ApiBuilderExercise = {
  name: string;
  sets: number;
  reps: string;
  rest: string;
  muscle: string;
  notes?: string | null;
};

export type ApiBuilderWorkout = {
  name: string;
  type: string;
  duration: string;
  exercises: ApiBuilderExercise[];
};

export type ApiBuilderDayInput = {
  label?: string;
  isRestDay: boolean;
  meals: ApiBuilderMeal[];
  workout?: ApiBuilderWorkout | null;
};

export type ApiCoachProgramDay = {
  id: string;
  dayNumber: number;
  label: string;
  date: string;
  isRestDay: boolean;
  meals?: Array<ApiBuilderMeal & { id: string }>;
  workout?: (ApiBuilderWorkout & { id: string }) | null;
};

export type ApiCoachProgram = {
  id: string;
  userId: string | null;
  coachRequestId: string | null;
  status: ApiProgramStatus;
  title: string;
  goal: string;
  level: string;
  calories: number;
  startDate: string | null;
  user?: { id: string; name: string } | null;
  weekPlan?: ApiCoachProgramDay[];
};